"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { storeSchema } from "@/features/stores/schemas/store-schema";
import { createClient } from "@/lib/supabase/server";
export type StoreActionState={message?:string;success?:boolean;fieldErrors?:Record<string,string[]>};
const storeIdSchema = z.string().uuid();
function revalidateStorePages(){ revalidatePath("/stores"); revalidatePath("/purchases"); revalidatePath("/purchases/new"); revalidatePath("/dashboard"); }
export async function createStore(_:StoreActionState,formData:FormData):Promise<StoreActionState>{ const parsed=storeSchema.safeParse({name:formData.get("name"),defaultChannel:formData.get("defaultChannel"),website:formData.get("website")||undefined,notes:formData.get("notes")||undefined,favorite:formData.get("favorite")==="true"}); if(!parsed.success)return{message:"Review the store details.",fieldErrors:parsed.error.flatten().fieldErrors as Record<string,string[]>}; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return{message:"Please sign in again."}; const v=parsed.data; const {error}=await supabase.from("stores").insert({user_id:user.id,name:v.name,default_channel:v.defaultChannel,website:v.website||null,notes:v.notes||null,is_favorite:v.favorite}); if(error)return{message:error.code==="23505"?"This store already exists.":error.message}; revalidateStorePages();return{success:true}; }
export async function archiveStore(id: string): Promise<StoreActionState> { const parsed=storeIdSchema.safeParse(id); if(!parsed.success)return{message:"Invalid store."}; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return{message:"Please sign in again."}; const {error}=await supabase.from("stores").update({is_active:false}).eq("id",parsed.data).eq("user_id",user.id).eq("is_active",true); if(error)return{message:error.message}; revalidateStorePages(); return{success:true}; }
export async function restoreStore(id: string): Promise<StoreActionState> { const parsed=storeIdSchema.safeParse(id); if(!parsed.success)return{message:"Invalid store."}; const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return{message:"Please sign in again."}; const {error}=await supabase.from("stores").update({is_active:true}).eq("id",parsed.data).eq("user_id",user.id).eq("is_active",false); if(error)return{message:error.code==="23505"?"An active store with this name already exists.":error.message}; revalidateStorePages(); return{success:true}; }
