"use client";
import { useActionState,useMemo,useState } from "react";import Link from "next/link";import { Globe2,Loader2,MapPin,ReceiptText,ShoppingBasket,Sparkles,Store as StoreIcon } from "lucide-react";
import { Button,buttonVariants } from "@/components/ui/button";import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";import { Input } from "@/components/ui/input";import { Label } from "@/components/ui/label";import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";import { Textarea } from "@/components/ui/textarea";import type { AccountWithBalance } from "@/features/accounts/types/account";import { createPurchase,updatePurchase,type PurchaseActionState } from "@/features/purchases/actions/purchase-actions";import { PurchaseItemsEditor } from "@/features/purchases/components/purchase-items-editor";import { PurchaseTotalsCard } from "@/features/purchases/components/purchase-totals-card";import type { ProductSuggestion,PurchaseFormInitialData,PurchaseItemInput,Store } from "@/features/purchases/types/purchase";import { calculatePurchaseTotals } from "@/features/purchases/utils/purchase-calculations";import type { Category } from "@/features/transactions/types/transaction";import { cn } from "@/lib/utils";
const initialState:PurchaseActionState={};const firstItem=():PurchaseItemInput=>({clientId:crypto.randomUUID(),name:"",quantity:1,unit:"piece",unitPrice:0,categoryId:""});const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
type Props={accounts:AccountWithBalance[];categories:Category[];stores:Store[];products:ProductSuggestion[];purchaseId?:string;initialData?:PurchaseFormInitialData};
export function PurchaseForm({accounts,categories,stores,products,purchaseId,initialData}:Props){const expenseCategories=categories.filter(c=>c.transaction_type==="expense");const[accountId,setAccountId]=useState(initialData?.accountId??accounts[0]?.id??"");const[categoryId,setCategoryId]=useState(initialData?.categoryId??expenseCategories.find(c=>/grocer|food|shopping/i.test(c.name))?.id??expenseCategories[0]?.id??"");const[storeId,setStoreId]=useState(initialData?.storeId??stores[0]?.id??"");const selectedStore=stores.find(s=>s.id===storeId);const[channel,setChannel]=useState<"online"|"physical">(initialData?.channel??selectedStore?.default_channel??"online");const[items,setItems]=useState<PurchaseItemInput[]>(initialData?.items?.length?initialData.items:[firstItem()]);const[tax,setTax]=useState(initialData?.tax??0);const[discount,setDiscount]=useState(initialData?.discount??0);const[deliveryFee,setDeliveryFee]=useState(initialData?.deliveryFee??0);const[receiptTotal,setReceiptTotal]=useState(initialData?.total??0);const formAction=purchaseId?updatePurchase.bind(null,purchaseId):createPurchase;const[state,action,pending]=useActionState(formAction,initialState);const account=accounts.find(a=>a.id===accountId);const category=expenseCategories.find(c=>c.id===categoryId);const totals=useMemo(()=>calculatePurchaseTotals(items,tax,discount,channel==="online"?deliveryFee:0),[items,tax,discount,deliveryFee,channel]);
function changeStore(value:string){setStoreId(value);const store=stores.find(s=>s.id===value);if(store){setChannel(store.default_channel);if(store.default_channel==="physical")setDeliveryFee(0)}}
return <form action={action} className="space-y-6" aria-busy={pending}><input type="hidden" name="accountId" value={accountId}/><input type="hidden" name="categoryId" value={categoryId}/><input type="hidden" name="storeId" value={storeId}/><input type="hidden" name="channel" value={channel}/><input type="hidden" name="items" value={JSON.stringify(items)}/>
<Card className="border-amber-500/20 bg-gradient-to-br from-amber-500/10 via-card to-transparent"><CardHeader><CardTitle className="flex items-center gap-2"><span className="flex size-9 items-center justify-center rounded-xl bg-amber-500/15 text-amber-600"><ShoppingBasket className="size-4"/></span>Receipt details</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2">
<div className="space-y-2"><div className="flex items-center justify-between"><Label>Store</Label><Link href="/stores" className="text-xs font-medium text-amber-600 hover:underline">Manage stores</Link></div><Select value={storeId} onValueChange={v=>v&&changeStore(v)}><SelectTrigger className="h-9 w-full"><span>{selectedStore?.name??"Select store"}</span><SelectValue className="sr-only" /></SelectTrigger><SelectContent>{stores.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select>{!stores.length?<p className="text-xs text-destructive">Add a store first from Stores.</p>:null}</div>
<div className="space-y-2"><Label>Shopping method</Label><div className="grid grid-cols-2 gap-2 rounded-xl bg-background/60 p-1"><button type="button" onClick={()=>setChannel("online")} className={cn("flex h-9 items-center justify-center gap-2 rounded-lg text-sm font-medium transition",channel==="online"?"bg-card text-foreground shadow-sm":"text-muted-foreground")}><Globe2 className="size-4"/>Online</button><button type="button" onClick={()=>{setChannel("physical");setDeliveryFee(0)}} className={cn("flex h-9 items-center justify-center gap-2 rounded-lg text-sm font-medium transition",channel==="physical"?"bg-card text-foreground shadow-sm":"text-muted-foreground")}><MapPin className="size-4"/>Physical</button></div></div>
{channel==="physical"?<div className="space-y-2"><Label htmlFor="branchName">Branch <span className="text-muted-foreground">optional</span></Label><Input id="branchName" name="branchName" placeholder="Dubai Festival City" defaultValue={initialData?.branchName??""}/></div>:<div className="space-y-2"><Label>Online store</Label><div className="flex h-9 items-center gap-2 rounded-lg border border-input bg-background/40 px-3 text-sm text-muted-foreground"><StoreIcon className="size-4"/>{selectedStore?.website??selectedStore?.name??"Select a store"}</div></div>}
<div className="space-y-2"><Label>Paid from</Label><Select value={accountId} onValueChange={v=>v&&setAccountId(v)}><SelectTrigger className="h-9 w-full"><span>{account?`${account.name} · ${account.currency}`:"Select account"}</span><SelectValue className="sr-only" /></SelectTrigger><SelectContent>{accounts.map(a=><SelectItem key={a.id} value={a.id}>{a.name} · {a.currency}</SelectItem>)}</SelectContent></Select></div>
<div className="space-y-2"><Label>Main category</Label><Select value={categoryId} onValueChange={v=>v&&setCategoryId(v)}><SelectTrigger className="h-9 w-full"><span>{category?.name??"Select category"}</span><SelectValue className="sr-only" /></SelectTrigger><SelectContent>{expenseCategories.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div>
<div className="space-y-2"><Label htmlFor="purchaseDate">Date</Label><Input id="purchaseDate" name="purchaseDate" type="date" defaultValue={initialData?.purchaseDate??today()} required/></div><div className="space-y-2"><Label htmlFor="notes">Notes</Label><Textarea id="notes" name="notes" rows={2} placeholder="Weekly groceries..." defaultValue={initialData?.notes??""}/></div></CardContent></Card>
<Card className="border-amber-500/15 bg-gradient-to-br from-amber-500/5 via-card to-transparent"><CardHeader><CardTitle className="flex items-center gap-2"><ReceiptText className="size-4 text-amber-500"/>Items</CardTitle></CardHeader><CardContent><PurchaseItemsEditor items={items} categories={expenseCategories} products={products} currency={account?.currency??"AED"} onChange={setItems}/></CardContent></Card>
<PurchaseTotalsCard subtotal={totals.subtotal} tax={tax} discount={discount} deliveryFee={deliveryFee} showDeliveryFee={channel==="online"} receiptTotal={receiptTotal} currency={account?.currency??"AED"} calculatedTotal={totals.total} onTaxChange={setTax} onDiscountChange={setDiscount} onDeliveryFeeChange={setDeliveryFee} onReceiptTotalChange={setReceiptTotal}/>{state.message?<p className="rounded-xl bg-destructive/10 px-4 py-3 text-sm text-destructive">{state.message}</p>:null}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Link href={purchaseId?`/purchases/${purchaseId}`:"/purchases"} className={cn(buttonVariants({variant:"outline"}),pending&&"pointer-events-none opacity-50")}>Cancel</Link><Button type="submit" disabled={pending||!storeId||Math.abs(totals.total-receiptTotal)>0.02||items.some(i=>!i.name.trim())}>{pending?<Loader2 className="size-4 animate-spin"/>:<Sparkles className="size-4"/>}{pending?(purchaseId?"Updating purchase...":"Saving receipt..."):(purchaseId?"Update purchase":"Save purchase")}</Button></div></form>}
